from core.gamesocket import GameSocket
from core import Player


class Connection(GameSocket):
    running: bool
    __server_address: tuple[str, int]

    def __init__(self, server_address: tuple[str, int]) -> None: ...
    @property
    def server_address(self) -> tuple[str, int]: ...
    def receive_player_data(self) -> None: ...
    def send_update(self, player: Player) -> None: ...
    @staticmethod
    def update_player(player: Player, update_from: dict) -> None: ...
