hivename: const
keys:
  AK47_COOLDOWN: .1
  AK47_DAMAGE: 1
  AK47_MAG_SIZE: 30
  AK47_RELOAD_TIME: 2.5
  AK47_SPEED: 730.3

  MINIGUN_COOLDOWN: .02
  MINIGUN_DAMAGE: 3
  MINIGUN_MAG_SIZE: 3000
  MINIGUN_INACCURACY: 0.0001093606
  MINIGUN_RELOAD_TIME: 30
  MINIGUN_SPEED: 850

  CIWS_COOLDOWN: .013
  CIWS_DAMAGE: 10
  CIWS_MAG_SIZE: 1550
  CIWS_INACCURACY: 0.0000193606
  CIWS_RELOAD_TIME: 55
  CIWS_SPEED: 1100
  CIWS_MAX_RANGE: 1486
  CIWS_ANGLE_RANGE: [-25, 85]
  CIWS_ANGLE_SPEED: 1.5009831567


  HOMING_ROCKET_COOLDOWN: .1
  HOMING_ROCKET_DAMAGE: 50
  HOMING_ROCKET_MAG_SIZE: 1
  HOMING_ROCKET_RELOAD_TIME: 30
  HOMING_ROCKET_SPEED: 50

  ROCKET_COOLDOWN: .1
  ROCKET_DAMAGE: 100
  ROCKET_MAG_SIZE: 1
  ROCKET_RELOAD_TIME: 20
  ROCKET_SPEED: 100

  SNIPER_DAMAGE: 9
  SNIPER_COOLDOWN: 4
  SNIPER_MAG_SIZE: 10
  SNIPER_INACCURACY: 0.0000500002
  SNIPER_RELOAD_TIME: 10
  SNIPER_SPEED: 1023

  g: 9.81
  PI: 3.1415926535897932384626433832795028841971

  PIXELS_PER_METER: 1
  JUMP_SPEED: 50
  MAX_HP: 100
  MAX_SPEED: 50
  WINDOW_SIZE:
  - 1920
  - 1080
writeprotect: true
